# Generated by Django 6.0.4 on 2026-04-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('business_model', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_segment_niche', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Startups',
            },
        ),
        migrations.CreateModel(
            name='StartupUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('opportunities_and_challenges', models.TextField(blank=True, null=True)),
                ('fundraising_updates', models.TextField(blank=True, null=True)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('risks', models.TextField(blank=True, null=True)),
                ('asks', models.TextField(blank=True, null=True)),
                ('people', models.TextField(blank=True, null=True)),
                ('period_label', models.CharField(blank=True, max_length=255, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='dashboard.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('change', models.CharField(blank=True, max_length=255, null=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.startupupdate')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_structure', models.CharField(blank=True, max_length=255, null=True)),
                ('total_capital_raised', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('invested_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('moic', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('irr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='dashboard.firm')),
            ],
        ),
        migrations.AddField(
            model_name='startupupdate',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_updates', to='dashboard.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='startupupdate',
            unique_together={('vehicle', 'startup', 'quarter', 'year')},
        ),
        migrations.CreateModel(
            name='QuarterlyLPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('summary_of_progress', models.TextField(blank=True, null=True)),
                ('new_investments', models.TextField(blank=True, null=True)),
                ('exits_and_distributions', models.TextField(blank=True, null=True)),
                ('governance_and_legal', models.TextField(blank=True, null=True)),
                ('significant_developments', models.TextField(blank=True, null=True)),
                ('asks_by_portfolio_companies', models.TextField(blank=True, null=True)),
                ('esg_updates', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lp_reports', to='dashboard.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'quarter', 'year')},
            },
        ),
        migrations.CreateModel(
            name='VehicleStartup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesis', models.TextField(blank=True, null=True)),
                ('role_of_fund', models.TextField(blank=True, null=True)),
                ('exit_strategy', models.CharField(blank=True, max_length=255, null=True)),
                ('stage_of_investment', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_investment', models.DateField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.startup')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Companies',
                'unique_together': {('vehicle', 'startup')},
            },
        ),
    ]
