# Generated by Django 6.0.4 on 2026-04-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupUpdateManager',
            fields=[
            ],
            options={
                'verbose_name': 'Startup Update',
                'verbose_name_plural': 'Startup Updates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard.startup',),
        ),
    ]
