# Generated by Django 6.0.4 on 2026-04-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_startupupdatemanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startup',
            options={'ordering': ['name'], 'verbose_name_plural': 'Startups'},
        ),
    ]
